source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "webrick"
gem "jekyll-theme-cayman"

# Plugins
gem "jekyll-relative-links"
gem "jekyll-sitemap"
gem "jekyll-feed"

# GitHub Pages compatibility
gem "github-pages", "~> 231", group: :jekyll_plugins